apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring
  name: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  strategy: {}
  template:
    metadata:
      labels:
        deployment-isolated-network: "true"
        app: spring
    spec:
      containers:
        - image: fadidasus/spring-mini-twit-backend
          name: spring-backend
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "524288e3"
      restartPolicy: Always
