apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: go
      name: go
    spec:
      ports:
        - name: "9000"
          port: 9000
          targetPort: 9000
      selector:
        app: go
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: mongo
      name: mongo
    spec:
      ports:
        - name: "27017"
          port: 27017
          targetPort: 27017
      selector:
        app: mongo
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: react
      name: react
    spec:
      ports:
        - name: "3000"
          port: 3000
          targetPort: 3000
      selector:
        app: react
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: spring
      name: spring
    spec:
      ports:
        - name: "8080"
          port: 8080
          targetPort: 8080
      selector:
        app: spring
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: go
      name: go
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: go
      strategy: {}
      template:
        metadata:
          labels:
            deployment-isolated-network: "true"
            app: go
        spec:
          containers:
            - image: fadidasus/go-mini-twit-simulator
              name: go-simulator
              ports:
                - containerPort: 9000
              resources:
                limits:
                  memory: "524288e3"
          restartPolicy: Always
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: deployment-isolated-network
    spec:
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  deployment-isolated-network: "true"
      podSelector:
        matchLabels:
          deployment-isolated-network: "true"
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: mongo
      name: mongo
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: mongo
      strategy: {}
      template:
        metadata:
          labels:
            deployment-isolated-network: "true"
            app: mongo
        spec:
          containers:
            - image: mongo
              name: mongo
              ports:
                - containerPort: 27017
              resources: {}
          restartPolicy: Always
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: react
      name: react
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: react
      strategy: {}
      template:
        metadata:
          labels:
            deployment-isolated-network: "true"
            app: react
        spec:
          containers:
            - image: fadidasus/react-mini-twit-frontend
              name: react-frontend
              ports:
                - containerPort: 3000
              resources:
                limits:
                  memory: "262144e3"
          restartPolicy: Always
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: spring
      name: spring
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: spring
      strategy: {}
      template:
        metadata:
          labels:
            deployment-isolated-network: "true"
            app: spring
        spec:
          containers:
            - image: fadidasus/spring-mini-twit-backend:2
              name: spring-backend
              ports:
                - containerPort: 8080
              resources:
                limits:
                  memory: "524288e3"
          restartPolicy: Always
kind: List
metadata: {}

