#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6-jdk-11-slim
definitions:
  services:
    mongo:
      image: mongo
  steps:
    - buildandtest: &buildandtest
        name: Build and Test
        caches:
          - maven
        services:
          - mongo
        script:
          - export LOCAL_CONNECTION_STRING="$LOCAL_CONNECTION_STRING"
          - export COSMOS_CONNECTION_STRING="$COSMOS_CONNECTION_STRING"
          - mvn -B verify
        artifacts:
          - target/*.jar
    - dockerize: &dockerize
        name: Create and Publish Docker Image
        services:
          - docker
        caches:
          - docker
        script:
          - docker build -t $APP_NAME:$BITBUCKET_COMMIT .
          - docker tag $APP_NAME:$BITBUCKET_COMMIT $AZ_DOCKER_SERVER/$APP_NAME:$BITBUCKET_COMMIT
          - docker login -u $AZ_DOCKER_USERNAME -p $AZ_DOCKER_PASSWORD $AZ_DOCKER_SERVER
          - docker push $AZ_DOCKER_SERVER/$APP_NAME:$BITBUCKET_COMMIT
pipelines:
  default:
    - step: *buildandtest
    - step: *dockerize

